// src/components/UI/Loader/MyLoader.vue
<template>
  <div class="loader" v-show="visible">
    <div class="dot" />
    <div class="dot" />
    <div class="dot" />
    <div class="dot" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'my-loader',
  props: {
    visible: {
      type: Boolean,
      required: true,
    },
  },
});
</script>

<style scoped lang="scss">
@import "./Loader.scss";
</style>

// src/components/UI/MyLoader/MyLoader.tsx
import React from 'react';
import styles from './MyLoader.module.scss';

interface MyLoaderProps {
  visible: boolean;
}

const MyLoader: React.FC<MyLoaderProps> = ({ visible }) => {
  if (!visible) {
    return null;
  }

  return (
    <div className={styles.loader}>
      <div className={styles.dot} />
      <div className={styles.dot} />
      <div className={styles.dot} />
      <div className={styles.dot} />
    </div>
  );
};

export default MyLoader;
