// src/views/Settings/Settings.vue
<template>
  <div class="settings">
    <div class="header">
      Settings
    </div>
    <draggable
      :list="cities"
      item-key="id"
      class="list"
      ghost-class="ghost"
    >
      <template #item="{ element }">
        <li class="list-item">
          <div class="left">
            <div class="menu">
              <icon-menu />
            </div>
            <span class="name">
              {{element.name}}
            </span>
          </div>

          <my-button size="s" @click="store.removeCity(element)">
            <icon-delete />
          </my-button>
        </li>
      </template>
    </draggable>

    <div class="add-city">
      <span class="title">
        Add Location
      </span>
      <add-city />
    </div>
  </div>
</template>

<script lang="ts">
import { useWeatherStore } from '@/stores';
import { computed, defineComponent } from 'vue';
import { MenuOutlined as IconMenu, DeleteOutlined as IconDelete } from '@ant-design/icons-vue';
import AddCity from '@/components/AddCity/AddCity.vue';
import draggable from 'vuedraggable';

const Settings = defineComponent({
  name: 'settings-view',
  components: {
    IconDelete,
    IconMenu,
    AddCity,
    draggable,
  },
  setup() {
    const store = useWeatherStore();

    return { store, cities: computed(() => store.cities) };
  },
});
export default Settings;
</script>

<style scoped lang="scss">
@import './Settings.scss';
</style>

// src/views/Settings/Settings.tsx
import React from 'react';
import { City } from '../../interfaces';
import styles from './Settings.module.scss';
import { ReactSortable } from 'react-sortablejs';
import {
  MenuOutlined as IconMenu,
  DeleteOutlined as IconDelete,
} from '@ant-design/icons';
import { MyButton } from '../../components/UI';
import { AddCity } from '../../components';
import useWeatherStore from '../../stores/weather/weather';

interface SettingsViewProps {}

const SettingsView: React.FC<SettingsViewProps> = () => {
  const store = useWeatherStore();

  const handleSetList = (values: City[]) => {
    store.setCities(values);
  };

  const handleClick = (city: City) => {
    store.removeCity(city);
  };

  return (
    <div className={styles.wrapper}>
      <div className={styles.header}>Settings</div>

      <ReactSortable
        list={store.cities}
        setList={handleSetList}
        tag="ul"
        className={styles.list}
      >
        {store.cities.map((el: City) => (
          <li className={styles.item} key={el.id}>
            <div className={styles.left}>
              <div className={styles.menu}>
                <IconMenu />
              </div>
              <span className={styles.name}>{el.name}</span>
            </div>

            <MyButton size="s" onClick={() => handleClick(el)}>
              <IconDelete />
            </MyButton>
          </li>
        ))}
      </ReactSortable>

      <div className={styles.addCity}>
        <span className={styles.title}>Add Location</span>
        <AddCity />
      </div>
    </div>
  );
};

export default SettingsView;
