// src/components/UI/MyButton/MyButton.vue
<template>
	<div
		class="btn"
		:class="{
      small : size === 's',
      middle: size=== 'm',
      large: size === 'l'
    }">
		<slot></slot>
	</div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'my-button',
  props: {
    size: {
      type: String as PropType<'s' | 'm' | 'l'>,
      default: 'm',
    },
  },
});
</script>

<style scoped lang="scss">
@import './MyButton.scss';
</style>

// src/components/UI/MyButton/MyButton.tsx
import React from 'react';
import styles from './MyButton.module.scss';
import cn from 'classnames';
import { DetailedHTMLProps, HTMLAttributes } from 'react';

interface MyButtonProps
  extends DetailedHTMLProps<
    HTMLAttributes<HTMLButtonElement>,
    HTMLButtonElement
  > {
  children: React.ReactNode;
  size?: 's' | 'm' | 'l';
}

const MyButton: React.FC<MyButtonProps> = ({ children, size = 'm' }) => {
  return (
    <button
      className={cn(styles.btn, {
        [styles.small]: size === 's',
        [styles.middle]: size === 'm',
        [styles.large]: size === 'l',
      })}
    >
      {children}
    </button>
  );
};

export default MyButton;
