// src/components/Error/Error.vue
<template>
  <div class="wrapper">
	<div class="title">
		Произошла ошибка
	</div>
	<div class="content">
		{{ error }}
	</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'error-component',
  props: {
    error: {
      type: String,
    },
  },
});
</script>

<style scoped lang="scss">
@import './Error.scss'
</style>

// src/components/Error/Error.tsx
import React from 'react';
import styles from './Error.module.scss';

interface ErrorProps {
  error: string;
}

const Error: React.FC<ErrorProps> = ({ error }) => {
  return (
    <div className={styles.wrapper}>
      <div className={styles.title}>Произошла ошибка</div>
      <div className={styles.content}>{error}</div>
    </div>
  );
};

export default Error;
