// src/components/WeatherCard/WeatherCard.tsx
import React from 'react';
import { City } from '../../interfaces';
import styles from './WeatherCatd.module.scss';
import {
  DashboardOutlined as IconPressure,
  SendOutlined as IconArrow,
} from '@ant-design/icons';

interface WeatherCatdProps {
  city: City;
}

const WeatherCatd: React.FC<WeatherCatdProps> = ({ city }) => {
  const imgUrl = `${process.env.REACT_APP_IMAGE_URL}/${city.icon}@2x.png`;
  const windIconStyle = { transform: 'rotate(${city.wind.deg + 180}deg);' };

  return (
    <div className={styles.wrapper}>
      <div className={styles.title}>
        {city.name}, {city.country}
      </div>
      <div className={styles.weather}>
        <img src={imgUrl} alt="weather icon" />
        <div className={styles.deg}>
          <strong>{city.temperature}&deg;C</strong>
        </div>
      </div>

      <div className={styles.description}>
        Feels like {city.feelsLike}&deg;C.
        <span className={styles.descriptionWeather}>
          {city.weatherDescription}. {city.wind.description}
        </span>
      </div>

      <div className={styles.params}>
        <p>
          <span className={styles.arrowIcon}>
            <IconArrow style={windIconStyle} />
          </span>
          {city.wind.speed} m/s {city.wind.direction}
        </p>
        <p>
          <IconPressure />
          {city.pressure} hPa
        </p>
        <p>Humidity: {city.humidity}</p>
        <p>Dew point: {city.dewPoint}</p>
        <p>Visibility: {city.visibility} km</p>
      </div>
    </div>
  );
};

export default WeatherCatd;

// src/components/WeatherCard/WeatherCard.vue
<template>
  <div class="city-wrapper">
    <div class="title">
      {{city.name}}, {{ city.country}}
    </div>
    <div class="weather">
      <img :src="imgUrl" alt="weather icon">
      <div class="deg">
        <strong>{{city.temperature}}&deg;C</strong>
      </div>
    </div>

    <div class="description">
      Feels like {{city.feelsLike}}&deg;C.
      <span class="weather-description">
        {{city.weatherDescription}}. {{city.wind.description}}
      </span>
    </div>

    <div class="params">
      <p>
        <span class="arrow-icon">
          <icon-arrow :style="windIconStyle" />
        </span>
        {{city.wind.speed}} m/s {{city.wind.direction}}
      </p>
      <p>
        <icon-pressure />
        {{city.pressure}} hPa
      </p>
      <p>
        Humidity: {{city.humidity}}%
      </p>
      <p>
        Dew point: {{city.dewPoint}}&deg;C
      </p>
      <p>
        Visibility: {{city.visibility}} km
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';
import { City } from '@/interfaces';
import { DashboardOutlined as IconPressure, SendOutlined as IconArrow } from '@ant-design/icons-vue';

export default defineComponent({
  name: 'weather-card',
  components: { IconPressure, IconArrow },
  data() {
    const imgUrl = `${process.env.VUE_APP_IMAGE_URL}/${this.city.icon}@2x.png`;
    const windIconStyle = `transform: rotate(${this.city.wind.deg + 180}deg);`;

    return {
      imgUrl,
      windIconStyle,
    };
  },
  props: {
    city: {
      type: Object as PropType<City>,
      required: true,
    },
  },
});
</script>

<style scoped lang="scss">
@import "./WeatherCard.scss";
</style>
