// src/views/Weather/Weather.vue
<template>
  <div class="weather-wrapper">
    <div
      v-if="store.cities.length === 0"
      class="empty"
    >
      <div class="title">
        It looks like there's nothing here
      </div>
      <div class="add-city">
        <add-city />
      </div>
    </div>
    <ul
      v-else
      class="weather-list"
    >
      <li
        v-for="city in store.cities"
        :key="city.id"
        class="city"
      >
        <weather-card :city="city" />
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { useWeatherStore } from '@/stores';
import { defineComponent } from 'vue';
import { WeatherCard, AddCity } from '@/components';

export default defineComponent({
  name: 'weather-view',
  components: {
    WeatherCard,
    AddCity,
  },
  setup() {
    const store = useWeatherStore();

    return {
      store,
    };
  },
  mounted() {
    if (!this.store.cities.length) {
      this.store.getLocation();
    }
    this.store.loadDataForAllCities();
  },
});
</script>

// src/views/Weather/Weather.tsx
import React, { useEffect } from 'react';
import { AddCity, WeatherCard } from '@/components';
import { City } from '@/interfaces';
import useWeatherStore from '@/stores/weather/weather';
import styles from './Weather.module.scss';

interface WeatherViewProps {}

const WeatherView: React.FC<WeatherViewProps> = () => {
  const store = useWeatherStore();

  useEffect(() => {
    if (!store.cities.length) {
      store.getLocation();
    }
    store.loadDataForAllCities();
  }, []);

  return (
    <div className={styles.wrapper}>
      {store.cities.length === 0 ? (
        <div className={styles.empty}>
          <div className={styles.title}>It looks like there's nothing here</div>
          <div className={styles.addCity}>
            <AddCity />
          </div>
        </div>
      ) : (
        <ul className={styles.list}>
          {store.cities.map((el: City) => (
            <li key={el.id} className={styles.city}>
              <WeatherCard key={el.id} city={el} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default WeatherView;
