// src/components/AddCity/AddCity.vue
<template>
	<div class="wrapper">
		<div class="error" v-show="store.errorAddCity && showError">
			{{store.errorAddCity}}
		</div>
		<div class="add-city">
			<input
				placeholder="Add Location"
				ref="input"
        @input="handleInput"
				@keyup.enter="handleAdd"
			/>
			<my-button @click="handleAdd">
				<enter-outlined />
			</my-button>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { EnterOutlined } from '@ant-design/icons-vue';
import { useWeatherStore } from '@/stores';

export default defineComponent({
  name: 'add-city',
  components: { EnterOutlined },
  data() {
    return {
      inputValue: '',
      showError: true,
    };
  },
  setup() {
    const store = useWeatherStore();
    const input = ref(null);

    return { input, store };
  },
  methods: {
    async handleAdd() {
      await this.store.addCity(this.inputValue);
      this.showError = true;
      this.inputValue = '';
      (this.$refs.input as HTMLInputElement).value = '';
    },
    focusInput() {
      (this.$refs.input as HTMLInputElement).focus();
    },
    handleInput(event: Event) {
      this.showError = false;
      this.inputValue = (event.target as HTMLInputElement).value;
    },
  },
  mounted() {
    this.focusInput();
  },
});
</script>

<style scoped lang="scss">
@import './AddCity.scss'
</style>

// src/components/AddCity/AddCity.tsx
import React, { useRef, useState, useEffect } from 'react';
import styles from './AddCity.module.scss';
import { EnterOutlined } from '@ant-design/icons';
import MyButton from '@/components/UI/MyButton/MyButton';
import useWeatherStore from '@/stores/weather/weather';

interface AddCityProps {}

const AddCity: React.FC<AddCityProps> = () => {
  const store = useWeatherStore();
  const [showError, setShowError] = useState<boolean>(false);
  const [inputValue, setInputValue] = useState<string>('');

  const inputRef = useRef<HTMLInputElement | null>(null);

  const focusInput = () => {
    inputRef.current?.focus();
  };

  useEffect(() => {
    focusInput();
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  const handleAdd = () => {
    store.addCity(inputValue);
    setShowError(false);
    setInputValue('');
  };

  const handleKeyUp = async (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleAdd();
    }
  };

  return (
    <div className={styles.wrapper}>
      {store.errorAddCity && showError && (
        <div className={styles.error}>{store.errorAddCity}</div>
      )}
      <div className={styles.controls}>
        <input
          ref={inputRef}
          placeholder="Add Location"
          onChange={handleChange}
          onKeyUp={handleKeyUp}
          value={inputValue}
        />
        <MyButton onClick={handleAdd}>
          <EnterOutlined />
        </MyButton>
      </div>
    </div>
  );
};

export default AddCity;
