// src/components/WeatherHeader/WeatherHeader.tsx
import React from 'react';
import { MyButton } from '@/components/UI';
import styles from './WeatherHeader.module.scss';
import { SettingOutlined, CloseOutlined } from '@ant-design/icons';
import { DetailedHTMLProps, HTMLAttributes } from 'react';

interface WeatherHeaderProps
  extends DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement> {
  showSettings: boolean;
}

const WeatherHeader: React.FC<WeatherHeaderProps> = ({
  showSettings,
  ...props
}) => {
  return (
    <div className={styles.wrapper} {...props}>
      {showSettings ? (
        <MyButton>
          <CloseOutlined />
        </MyButton>
      ) : (
        <MyButton>
          <SettingOutlined />
        </MyButton>
      )}
    </div>
  );
};

export default WeatherHeader;

// src/components/WeatherHeader/WeatherHeader.vue
<template>
	<div class="wrapper">
    <my-button v-show="!showSettings" class="btn">
      <setting-outlined
        class="icon"
      />
    </my-button>

    <my-button v-show="showSettings" class="btn">
      <close-outlined
        class="icon"
        v-show="showSettings"
      />
    </my-button>

	</div>

</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { SettingOutlined, CloseOutlined } from '@ant-design/icons-vue';

export default defineComponent({
  name: 'weather-header',
  components: { SettingOutlined, CloseOutlined },
  props: {
    showSettings: {
      type: Boolean,
      required: true,
    },
  },
});
</script>

<style scoped lang="scss">
@import './WeatherHeader.scss'
</style>
