// src/widgets/WeatherWidget/WeatherWidget.vue
<template>
  <div class="container">
    <my-card>
      <div class="header">
        <weather-header
          :showSettings="store.isSettingsOpen"
          @click="toggleSettings"
        />
      </div>
      <settings v-if="store.isSettingsOpen" />
      <weather v-else />
      <div class="loader-wrapper">
        <my-loader
          v-show="store.isLoading"
          :visible="store.isLoading"
        />
      </div>
      <div class="error-wrapper">
        <error-component
          v-if="store.error !== null" :error="store.error ?? ''"
        />
      </div>
    </my-card>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Settings, Weather } from '@/views';

import {
  WeatherHeader, ErrorComponent,
} from '@/components';
import { useWeatherStore } from '@/stores/weather';
import { saveToLocalStorage } from '@/helpers';
import { LS_WEATHER_STATE } from '@/constants';

export default defineComponent({
  name: 'weather-widget',
  components: {
    Weather,
    Settings,
    WeatherHeader,
    ErrorComponent,

  },
  setup() {
    const store = useWeatherStore();

    store.$subscribe((_, state) => {
      saveToLocalStorage(LS_WEATHER_STATE, state);
    });

    return { store };
  },
  methods: {
    toggleSettings() {
      this.store.toggleSettings();
      this.store.resetError();
      this.store.resetErrorAddCity();
    },
  },
});
</script>

<style lang="scss">
@import './WeatherWidget.scss'
</style>

// src/widgets/WeatherWidget/WeatherWidget.tsx
import React, { useEffect } from 'react';
import { WeatherHeader } from '../../components';
import { MyCard, MyLoader } from '../../components/UI';
import useWeatherStore from '../../stores/weather/weather';
import SettingsView from '../../views/Settings/Settings';
import WeatherView from '../../views/Weather/Weather';
import styles from './WeatherWidget.module.scss';

interface WeatherWidgetProps {
  timeout?: number;
}

const WeatherWidget: React.FC<WeatherWidgetProps> = ({ timeout = 30 }) => {
  const store = useWeatherStore();

  useEffect(() => {
    setInterval(async () => {
      store.loadDataForAllCities();
    }, timeout * 60 * 1000);
  }, []);

  const handleClick = () => {
    console.log('click header');
    store.toggleSettings();
    store.resetError();
    store.resetErrorAddCity();
  };

  return (
    <div className={styles.weatherWidget}>
      <MyCard>
        <div className={styles.widgetHeader}>
          <WeatherHeader
            showSettings={store.isSettingsOpen}
            onClick={handleClick}
          />
        </div>
        {store.isSettingsOpen ? <SettingsView /> : <WeatherView />}
        <div className={styles.loaderWrapper}>
          <MyLoader visible={store.isLoading} />
        </div>
      </MyCard>
    </div>
  );
};

export default WeatherWidget;
